MyToDoList/Controllers/ToDoEntriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyToDoList_Domain.Data;
using MyToDoList_Domain.Models;
using MyToDoList_Domain.Repository;

namespace ToDoListWebApplication.Controllers
{
    public class ToDoEntriesController : Controller
    {
        private readonly ToDoDbContext _context;
        private readonly IToDoRepository _repository;
        public ToDoEntriesController(ToDoDbContext context, IToDoRepository repository)
        {
            _context = context;
            _repository = repository;
        }

        // GET: ToDoEntries
        public async Task<IActionResult> Index()
        {
            var toDoListWebApplicationContext = _context.ToDoEntries.Include(t => t.ToDoList);
            return View(await toDoListWebApplicationContext.ToListAsync());
        }

        // GET: ToDoEntries/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var toDoEntries = await _context.ToDoEntries
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoEntries == null)
            {
                return NotFound();
            }

            return View(toDoEntries);
        }

        // GET: ToDoEntries/Create
        public IActionResult Create()
        {
            ViewData["ToDoListId"] = new SelectList(_context.Set<ToDoList>(), "Id", "ToDoListDescription");
            return View();
        }

        // POST: ToDoEntries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ToDoListId,Name,Description,Status,CreatedTime,ModifiedTime,AdditionalNotes,ReminderDate,DueDate,Hiden")] ToDoEntries toDoEntries)
        {
            if (!ModelState.IsValid)
            {
                await _repository.CreateEntryAsync(toDoEntries);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ToDoListId"] = new SelectList(_context.Set<ToDoList>(), "Id", "ToDoListDescription", toDoEntries.ToDoListId);
            return View(toDoEntries);
        }

        // GET: ToDoEntries/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.ToDoEntries == null)
            {
                return NotFound();
            }

            var toDoEntries = await _context.ToDoEntries.FindAsync(id);
            if (toDoEntries == null)
            {
                return NotFound();
            }
            ViewData["ToDoListId"] = new SelectList(_context.Set<ToDoList>(), "Id", "ToDoListDescription", toDoEntries.ToDoListId);
            return View(toDoEntries);
        }

        // POST: ToDoEntries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ToDoListId,Name,Description,Status,ModifiedTime,AdditionalNotes,ReminderDate,DueDate,Hiden")] ToDoEntries toDoEntries)
        {

            if (!ModelState.IsValid)
            {
                try
                {
                    await _repository.UpdateEntryAsync(toDoEntries);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoEntriesExists(toDoEntries.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ToDoListId"] = new SelectList(_context.Set<ToDoList>(), "Id", "ToDoListDescription", toDoEntries.ToDoListId);
            return View(toDoEntries);
        }

        // GET: ToDoEntries/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var toDoEntries = await _context.ToDoEntries
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoEntries == null)
            {
                return NotFound();
            }

            return View(toDoEntries);
        }

        // POST: ToDoEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ToDoEntries == null)
            {
                return Problem("Entity set 'ToDoListWebApplicationContext.ToDoEntries'  is null.");
            }
            var toDoEntries = await _context.ToDoEntries.FindAsync(id);
            if (toDoEntries != null)
            {
                _context.ToDoEntries.Remove(toDoEntries);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ToDoEntriesExists(int id)
        {
          return (_context.ToDoEntries?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MyToDoList/Controllers/ToDoListsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyToDoList_Domain.Data;
using MyToDoList_Domain.Models;
using MyToDoList_Domain.Repository;

namespace ToDoListWebApplication.Controllers
{
    public class ToDoListsController : Controller
    {
        private readonly ToDoDbContext _context;
        private readonly IToDoRepository _repository;
        public ToDoListsController(ToDoDbContext context, IToDoRepository repository)
        {
            _context = context;
            _repository = repository;
        }

        // GET: ToDoLists
        public async Task<IActionResult> Index()
        {
              return _context.ToDoLists != null ? 
                          View(await _context.ToDoLists.ToListAsync()) :
                          Problem("Entity set 'ToDoListsDbContext.ToDoList'  is null.");
        }

        // GET: ToDoLists/Details/5
        public async Task<IActionResult> Details(int id)
        {

            var toDoList = await _context.ToDoLists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoList == null)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        // GET: ToDoLists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToDoLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ToDoListName,ToDoListDescription,IsHidden")] ToDoList toDoList)
        {
            if (!ModelState.IsValid)
            {
                await _repository.CreateListAsync(toDoList);
                return RedirectToAction(nameof(Index));
            }
            return View(toDoList);
        }

        // GET: ToDoLists/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var toDoList = await _context.ToDoLists.FindAsync(id);
            if (toDoList == null)
            {
                return NotFound();
            }
            return View(toDoList);
        }

        // POST: ToDoLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ToDoListName,ToDoListDescription,IsHidden")] ToDoList toDoList)
        {
            if (id != toDoList.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDoList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoListExists(toDoList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(toDoList);
        }

        // GET: ToDoLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ToDoLists == null)
            {
                return NotFound();
            }

            var toDoList = await _context.ToDoLists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoList == null)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        // POST: ToDoLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ToDoLists == null)
            {
                return Problem("Entity set 'ToDoListsDbContext.ToDoList'  is null.");
            }
            var toDoList = await _context.ToDoLists.FindAsync(id);
            if (toDoList != null)
            {
                _context.ToDoLists.Remove(toDoList);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ToDoListExists(int id)
        {
          return (_context.ToDoLists?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MyToDoList/Views/ToDoLists/Create.cshtml
@model MyToDoList_Domain.Models.ToDoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div class="form-group"> 
                <label asp-for="ToDoListName" class="control-label"></label>
                <input asp-for="ToDoListName" class="form-control" />
                <span asp-validation-for="ToDoListName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDoListDescription" class="control-label"></label>
                <input asp-for="ToDoListDescription" class="form-control" />
                <span asp-validation-for="ToDoListDescription" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyToDoList/Views/ToDoLists/Delete.cshtml
@model MyToDoList_Domain.Models.ToDoList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoListName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDoListName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoListDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDoListDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsHidden)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsHidden)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyToDoList/Views/ToDoLists/Details.cshtml
@model MyToDoList_Domain.Models.ToDoList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ToDoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoListName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDoListName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDoListDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDoListDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsHidden)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsHidden)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyToDoList/Views/ToDoLists/Edit.cshtml
@model MyToDoList_Domain.Models.ToDoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ToDoListName" class="control-label"></label>
                <input asp-for="ToDoListName" class="form-control" />
                <span asp-validation-for="ToDoListName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDoListDescription" class="control-label"></label>
                <input asp-for="ToDoListDescription" class="form-control" />
                <span asp-validation-for="ToDoListDescription" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyToDoList/Views/ToDoLists/Index.cshtml
@model IEnumerable<MyToDoList_Domain.Models.ToDoList>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ToDoListName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToDoListDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsHidden)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ToDoListName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ToDoListDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsHidden)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a href="@Url.Action("Create", "ToDoEntries", new { id = item.Id })">AddEntry</a>
            </td>
        </tr>
}
    </tbody>
</table>